# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Atomic Witchcraft
description: > # this means to ignore newlines until "baseurl:"
    Hi! My name's Emily and I'm a PhD student in theoretical physics, working on numerical and
    computational techniques in atomic physics. I am co-author of the AMBiT software suite for 
    high-precision atomic structure calculations, and ended up becoming my group's high-performance
    computing specialist and all-around code witch. I'm a mostly self-taught developer; this blog is
    a place to document that learning process, as well as other computer sciencey things I find
    interesting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emilyviolet.github.io/" # the base hostname & protocol for your site
twitter_username: atomwitch
github_username:  emilyviolet

# Build settings
markdown: kramdown
theme: minima

timezone: Australia/Sydney
